### ISSUE TITLE
image doesn't round-trip

### ISSUE THREAD

**Issue by csrhodes** [slyrus/opticl#14]
Hi,

I'm not sure what's going on, but:

    (opticl:write-png-file "/tmp/tetris2.png" (opticl:read-png-file "/tmp/tetris.png"))

produces an output image which is substantially different from the input image, which you can find at <http://www.dangermouse.net/esoteric/piet/tetris.png>.  I think there's a problem with reading, but I'm not sure where.

**Comment by slyrus** [comment]
Hmm... Looks to me like we're getting bad data back from png-read.

**Comment by slyrus** [comment]
The first column is OK, but starting with the second column things go haywire.

**Comment by slyrus** [comment]
A bug in ramarren's png-read code. See https://github.com/Ramarren/png-read/pull/7 for the fix.

**Comment by slyrus** [comment]
Will close this when ramarren merges the pull-request.

**Comment by csrhodes** [comment]
Lovely.  Thank you.

**Comment by slyrus** [comment]
Thank you! This bug has been here a long time and I think I've run across it from time to time. This underscores the need for a more complete test suite for opticl.

**Comment by slyrus** [comment]
This is fixed in the latest png-read https://github.com/Ramarren/png-read/pull/7. Thanks again for the report!
