### ISSUE TITLE
Compiler warning from SBCL 1.3.11 in coerce.lisp

### ISSUE THREAD

**Issue by robert-strandh** [slyrus/opticl#15]
Compiling a fresh clone of opticl on SBCL 1.3.11 gives a warning for
coerce.lisp like this:

; file: .../Opticl/coerce.lisp
; in: DEFMETHOD COERCE-IMAGE (T (EQL 'GRAY-IMAGE))
;     (SETF (OPTICL:PIXEL OPTICL:GRAY-IMAGE OPTICL::I OPTICL::J)
;             (ROUND
;              (+ (* OPTICL::R 0.2989) (* OPTICL::G 0.587) (* OPTICL::B 0.114))))
; --> LET* MULTIPLE-VALUE-BIND MULTIPLE-VALUE-CALL FUNCTION 
; --> MULTIPLE-VALUE-PROG1 PROGN ECASE LET COND IF PROGN LET 
; ==>
;   (ARRAY-DIMENSION OPTICL:GRAY-IMAGE 2)
; 
; caught WARNING:
;   The array has dimensions (* *), 2 is too large.

**Comment by slyrus** [comment]
Thanks for the report. A putative fix has been pushed. Let me know if this works.

**Comment by robert-strandh** [comment]
The warning is gone now.  Thanks!
