### ISSUE TITLE
Read CMYK jpeg files.

### ISSUE THREAD

**Issue by knobo** [slyrus/opticl#19]
With the latest  cl-jpeg package we can read cmyk files.
Here is an example on how to do it:

``` diff
--- jpeg.lisp.orig	2017-01-16 11:22:39.029990889 +0100
+++ jpeg.lisp	2017-01-16 11:41:02.245207289 +0100
@@ -5,6 +5,7 @@
 
 (defconstant +ncomp-gray+ 1)
 (defconstant +ncomp-rgb+ 3)
+(defconstant +ncomp-cmyk+ 4)
 
 (defparameter *rgb-sampling* '((1 1)(1 1)(1 1)))
 (defparameter *rgb-q-tabs* (vector jpeg::+q-luminance-hi+
@@ -16,9 +17,12 @@
 (defun read-jpeg-stream (stream)
   (multiple-value-bind (buffer height width ncomp)
       (jpeg:decode-stream stream)
-    (cond
-      ((= ncomp +ncomp-rgb+)
-       (let ((image (make-8-bit-rgb-image height width)))
+    (ecase ncomp
+      ((#.+ncomp-rgb+ #.+ncomp-cmyk+)
+       (let ((image (make-8-bit-rgb-image height width))
+             (buffer (if (eql +ncomp-cmyk+ ncomp)
+                         (jpeg:convert-cmyk-to-rgb buffer height width)
+                         buffer)))
          (declare (type 8-bit-rgb-image image))
          (loop for i below height
             do 
@@ -30,7 +34,7 @@
                                    (aref buffer (+ 1 pixoff))
                                    (aref buffer  pixoff))))))
          image))
-      ((= ncomp 1)
+      (#.+ncomp-gray+
        (let ((image (make-8-bit-gray-image height width))
              (pixoff 0))
          (declare (type 8-bit-gray-image image))
```

**Comment by knobo** [comment]
I was not able to compile the master branch so I did not provide a pull request. There was a missing tiff2 package.

**Comment by slyrus** [comment]
@knobo tiff2 is in the latest retrospectiff. thanks for the patch. i'll take a look in more detail later today.

**Comment by slyrus** [comment]
@knobo do you have any sample CMYK jpeg images? I don't think cl-jpeg lets me write CMYK images.

**Comment by knobo** [comment]
You can create with ImageMagick
convert -colorspace CMYK file-rbg.jpg file-cmyk.jpg
![white-cmyk](https://cloud.githubusercontent.com/assets/89921/22143955/3d949ebc-defc-11e6-81b9-a0003014c4f9.jpg)
![white](https://cloud.githubusercontent.com/assets/89921/22143960/40ac784a-defc-11e6-920b-dabbf886b56a.jpg)

**Comment by knobo** [comment]
In the example in my comment I used ImageMagics command "convert"
In case you don't have ImageMagic installed, I send the files here:
 
![test-cmyk](https://user-images.githubusercontent.com/89921/44987519-c4ae4080-af87-11e8-959c-5355f47e5543.jpg)
![test-rgb](https://user-images.githubusercontent.com/89921/44987520-c4ae4080-af87-11e8-9cdc-801e378eb525.jpg)

**Comment by slyrus** [comment]
Thanks for the suggestion. I've adapted your approach, modified it a bit and committed it.

**Comment by knobo** [comment]
Just out of curiosity, why do you use `let` instead of `for`
``` lisp
(loop for j below width
      do
         (let ((pixoff (* +ncomp-rgb+ (+ (* i width) j))))
           (setf (pixel image i j)
                 (values (aref buffer (+ 2 pixoff))
                         (aref buffer (+ 1 pixoff))
                         (aref buffer  pixoff)))))
```
instead of
``` lisp
(loop for j below width
      for pixoff = (* +ncomp-rgb+ (+ (* i width) j))
      do
         (setf (pixel image i j)
               (values (aref buffer (+ 2 pixoff))
                       (aref buffer (+ 1 pixoff))
                       (aref buffer  pixoff)))))
```
here: 
https://github.com/slyrus/opticl/commit/62f0cac8d0fd1a5b8ec8e91050fa2d8a27672274#diff-40c7cdb2998710d4b087f70030ca3b661c44a7bbccffcba0044c9befdbe87da2R27

I guess most lisp compilers would optimize it away, but to me it looks like `pixoff` would have to be allocated on every `do`
Maybe using the `let` would make it easier for the lisp implementation to inline it without ever using a variable.
