### ISSUE TITLE
The test uses short-float values when it really needs single-float

### ISSUE THREAD

**Issue by Yehouda** [slyrus/opticl#34]
The tests in test/opticl-test.lisp which want single-float use values like 1.0s0 which are short-float. It should use 'f' instead of 's': 1.0f0.

Cause test failures on implementations that distinguish between single-float and short-float.

Actually defined here: file:///C:/Program%20Files/LispWorks/lib/7-1-0-0/manual/online/CLHS/Body/26_glo_e.htm#exponent_marker

**Comment by slyrus** [comment]
Fixed. Thanks!
