### ISSUE TITLE
CMUCL / holograms

### ISSUE THREAD

**Issue by wpasieka** [slyrus/opticl#37]
Hello,

I have some issues with installing it on CMUCL, but need to investigate it carefully, possibly ask for help.

This is really a good idea to use the CL arrays, it gives the elegance and clarity.

I am wondering what could make a genius author of it to develop the package into the RGB-D + Machine Learning, to make it a holography ready :  )

http://cgh.csail.mit.edu/#Paper

**Comment by slyrus** [comment]
Sounds like this is some sort of feature request. I'm not quite sure. Closing.
