### ISSUE TITLE
opticl fails to load on CCL, Allegro

### ISSUE THREAD

**Issue by 3b** [slyrus/opticl#41]
CCL and Allegro complain about `Unbound variable: OPTICL::+NCOMP-RGB+` and `Attempt to take the value of the unbound variable `OPTICL::+NCOMP-RGB+'.`, presumably from use of `#.+ncomp-rgb+` in https://github.com/slyrus/opticl/blob/master/jpeg.lisp#L33-L38.

`+NCOMP-RGB+` is defined as a constant in the same file without `eval-when`, so is no guaranteed to have a value by the time the `#.+ncomp-rgb+` is read.

**Comment by 3b** [comment]
looks like #40 fixes both of those as well

**Comment by slyrus** [comment]
Should be fixed now. Thanks!
